---
server:
    install: '1'
    packages: [vim, git, htop, imagemagick, npm, nodejs, curl]
    timezone: Asia/Kuala_Lumpur
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: vagrant, ip: 192.168.100.10, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /usr/share/nginx/html
    servername: myApp.vb
pgsql:
    install: '1'
    database: brazil
    user: vagrant
    password: vagrant
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-pgsql]
